Code & Features Update

diff --git a/template b/template
--- a/template
+++ b/template
@@ -6,47 +6,72 @@ if [[ $(id -u -n) = "root" ]]
 then
 	SUDO_HOME=/root
 
-	USER="${SUDO_USER}"
+	USER="${SUDO_USER:-root}"
 
-	HOME=/home/"${USER}"
+	if [ "${USER}" = "root" ]
+	then
+		HOME=/root
+	else
+		HOME="/home/${USER}"
+	fi
 fi
 
 if [[ -z $(command -v curl) ]]
 then
-	yes | apt-get install curl
+	if [[ -n $(command -v apt-get) ]]
+	then
+		apt-get -q -q update > /dev/null 2>&1
+		apt-get -q -q install -y curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v dnf) ]]
+	then
+		dnf -q install -y curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v yum) ]]
+	then
+		yum -q install -y curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v apk) ]]
+	then
+		apk add --quiet curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v pacman) ]]
+	then
+		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v zypper) ]]
+	then
+		zypper --quiet --non-interactive install curl > /dev/null 2>&1
+	fi
 fi
 
-if [ ! -d "${HOME}"/.local/bin ]
+if [[ -z $(command -v curl) ]]
 then
-	mkdir -p "${HOME}"/.local/bin
+	echo "Unable to install curl."
+	echo
+
+	exit 1
 fi
+
+mkdir -p "${HOME}"/.local/bin
 
 frobulator="${HOME}"/.local/bin/frobulator
 
-version_online=$(curl -s -L get.frbltr.app | grep 'version=' | cut -d '"' -f 2)
+version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
 
-version_local=$(cat "${frobulator}" | grep 'version=' | cut -d '"' -f 2)
+version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)
 
 version_local="${version_local:-01-01-1970}"
 
-date_online=$(date -d "${version_online:6:4}-${version_online:0:2}-${version_online:3:2}" +%s)
+date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"
+date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"
 
-date_local=$(date -d "${version_local:6:4}-${version_local:0:2}-${version_local:3:2}" +%s)
-
-if [ -f "${frobulator}" ] && [ "${date_online}" -gt "${date_local}" ]
+if [ ! -f "${frobulator}" ] ||
+   [[ "${date_online}" > "${date_local}" ]]
 then
-	rm -r -f "${HOME}"/.local/bin/frobulator
+	curl -s -L get.frbltr.app > "${frobulator}"
 
-	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator
-
-	chmod +x "${HOME}"/.local/bin/frobulator
-fi
-
-if [ ! -f "${frobulator}" ]
-then
-	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator
-
-	chmod +x "${HOME}"/.local/bin/frobulator
+	chmod +x "${frobulator}"
 fi
 
 . "${frobulator}"
@@ -59,13 +84,94 @@ export self_arguments="${@}"
 
 # script ///////////////////////////////////////////////////////////////////////
 
-script="${BASH_SOURCE[0]}"
+script="$(basename -- ${BASH_SOURCE[0]})"
 
 # version //////////////////////////////////////////////////////////////////////
 
 version="MM-DD-YYYY"
 
 # usage ////////////////////////////////////////////////////////////////////////
+
+if [[ "${self}" = "${0}" ]]
+then
+	# implement from local version
+
+	if [ $# -eq 0 ]
+	then
+		source "${self}"
+
+		return 0 2> "${sink}"
+
+		if [ "${?}" -ne 0 ]
+		then
+			frobulator.scs "Implemented" "[ ${PWD}/${self} ]"
+			echo
+		fi
+	fi
+
+	file_source="${self}"
+
+	file_install="${file_source}"
+
+	directory_install="${HOME}"/.local/bin
+
+	file_target="${directory_install}/${file_install}"
+
+	while (($#))
+	do
+		case "${1}" in
+
+			-i|--install)
+
+				if [ ! -d "${directory_install}" ]
+				then
+					mkdir -p "${directory_install}"
+				fi
+
+				if [ "${file_source}" != "${file_target}" ]
+				then
+					cp "${file_source}" "${file_target}"
+
+					chmod a+rx "${file_target}"
+
+					source "${file_target}"
+
+					frobulator.scs "Installed" "[ ${file_target} ]"
+
+					echo
+				fi
+			;;
+
+			-h|--help)
+
+				echo
+				echo -e "Usage: ./${script} | [OPTION]"
+				echo
+				echo "Options:"
+				echo
+				echo "	-i, --install    [I]nstall "${script}" to ${directory_install}"
+				echo "	-h, --help       Show this [h]elp menu"
+				echo
+
+				exit
+			;;
+
+			*)
+
+				echo
+				echo "${script}: Unknown option '${1}'"
+				echo "Type './${script} --help' for help and usage information."
+				echo
+
+				exit 1
+			;;
+
+		esac
+
+		shift
+
+	done
+fi
 
 # prompt ///////////////////////////////////////////////////////////////////////
 
