Code & Features Update

diff --git a/utility-add-remove b/utility-add-remove
--- a/utility-add-remove
+++ b/utility-add-remove
@@ -67,69 +67,37 @@ version="07-18-2026"
 
 # usage ////////////////////////////////////////////////////////////////////////
 
+from=""
+to=""
+
+add=false
+remove=false
+
 execute=false
 confirm=true
-
-operation=""
 
 while (($#))
 do
 	case "${1}"
 	in
 		-f|--from)
-			if [ -z "${2}" ] || [[ "${2}" = -* ]]
-			then
-				echo
-				echo "${script}: Missing directory after '${1}'."
-				echo
-
-				exit 1
-			fi
-
 			from="${2}"
 
 			shift
 		;;
 
 		-t|--to)
-			if [ -z "${2}" ] || [[ "${2}" = -* ]]
-			then
-				echo
-				echo "${script}: Missing directory after '${1}'."
-				echo
-
-				exit 1
-			fi
-
 			to="${2}"
 
 			shift
 		;;
 
 		-a|--add)
-			if [ -n "${operation}" ] && [ "${operation}" != "add" ]
-			then
-				echo
-				echo "${script}: Add and remove cannot be used together."
-				echo
-
-				exit 1
-			fi
-
-			operation="add"
+			add=true
 		;;
 
 		-r|--remove)
-			if [ -n "${operation}" ] && [ "${operation}" != "remove" ]
-			then
-				echo
-				echo "${script}: Add and remove cannot be used together."
-				echo
-
-				exit 1
-			fi
-
-			operation="remove"
+			remove=true
 		;;
 
 		-e|--execute)
@@ -190,6 +158,7 @@ do
 
 			exit 1
 		;;
+
 	esac
 
 	shift
@@ -207,7 +176,7 @@ list_from="${temporary}/from.list"
 list_to="${temporary}/to.list"
 list_changes="${temporary}/changes.list"
 
-count_changes=0
+count_differential=0
 
 reply=""
 
@@ -222,6 +191,13 @@ then
 
 	exit 1
 
+elif [[ "${from}" = -* ]]
+then
+	frobulator.err "Missing argument for '--from'."
+	echo
+
+	exit 1
+
 elif [ -z "${to}" ]
 then
 	frobulator.err "Missing to directory."
@@ -229,16 +205,29 @@ then
 
 	exit 1
 
-elif [ -z "${operation}" ]
+elif [[ "${to}" = -* ]]
+then
+	frobulator.err "Missing argument for '--to'."
+	echo
+
+	exit 1
+
+elif [ "${add}" = true ] && [ "${remove}" = true ]
+then
+	frobulator.err "Add and remove cannot be used together."
+	echo
+
+	exit 1
+
+elif [ "${add}" = false ] && [ "${remove}" = false ]
 then
 	frobulator.err "Missing operation."
 	frobulator.nul "Specify either '--add' or '--remove'."
 	echo
 
 	exit 1
-fi
 
-if [ "${confirm}" = false ] && [ "${execute}" = false ]
+elif [ "${confirm}" = false ] && [ "${execute}" = false ]
 then
 	frobulator.err "'--yes' requires '--execute'."
 	echo
@@ -273,6 +262,17 @@ then
 	echo
 
 	exit 1
+fi
+
+# determine operation
+
+if [ "${add}" = true ]
+then
+	operation="add"
+
+elif [ "${remove}" = true ]
+then
+	operation="remove"
 fi
 
 # functions ////////////////////////////////////////////////////////////////////
@@ -423,19 +423,19 @@ then
 	comm -1 -3 "${list_from}" "${list_to}" > "${list_changes}"
 fi
 
-count_changes=$(wc -l < "${list_changes}")
+count_differential=$(wc -l < "${list_changes}")
 
 # display changes
 
-if [ "${count_changes}" -gt 0 ]
+if [ "${count_differential}" -gt 0 ]
 then
 	if [ "${operation}" = "add" ]
 	then
-		frobulator.add "Files to be added" "[ ${count_changes} ]"
+		frobulator.add "Files to be added" "[ ${count_differential} ]"
 
 	elif [ "${operation}" = "remove" ]
 	then
-		frobulator.rem "Files to be removed" "[ ${count_changes} ]"
+		frobulator.rem "Files to be removed" "[ ${count_differential} ]"
 	fi
 
 	echo
@@ -464,7 +464,7 @@ fi
 
 if [ "${execute}" = false ]
 then
-	frobulator.wrn "Dry run only" "[ ${operation}: ${count_changes} ]"
+	frobulator.wrn "Dry run only" "[ ${operation}: ${count_differential} ]"
 	frobulator.nul "Run ${script} again with '--execute' to apply changes."
 	echo
 
@@ -481,11 +481,11 @@ then
 
 	if [ "${operation}" = "add" ]
 	then
-		frobulator.ask "Proceed with adding ${count_changes} files?"
+		frobulator.ask "Proceed with adding ${count_differential} files?"
 
 	elif [ "${operation}" = "remove" ]
 	then
-		frobulator.ask "Proceed with removing ${count_changes} files?"
+		frobulator.ask "Proceed with removing ${count_differential} files?"
 	fi
 
 	frobulator.read reply
@@ -523,7 +523,7 @@ then
 		exit 1
 	fi
 
-	frobulator.inf "Files added to destination" "[ ${count_changes} ]"
+	frobulator.inf "Files added to destination" "[ ${count_differential} ]"
 	echo
 
 elif [ "${operation}" = "remove" ]
@@ -561,7 +561,7 @@ then
 		exit 1
 	fi
 
-	frobulator.inf "Files removed from destination" "[ ${count_changes} ]"
+	frobulator.inf "Files removed from destination" "[ ${count_differential} ]"
 	echo
 fi
 
