Code & Features Update

diff --git a/utility-conky-picture-selector b/utility-conky-picture-selector
--- a/utility-conky-picture-selector
+++ b/utility-conky-picture-selector
@@ -1,65 +1,70 @@
 #!/bin/bash
 
-# dependencies #
-
-curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator
-
-# variables #
-
-[[ $(id -u -n) = "root" ]] && home=/home/"${SUDO_USER:-$USER}" || home=/home/"${USER}"
-configuration_directory="${HOME}"/.config
-
-# configuration #
 
 cat << "FILE" > /usr/bin/conky-picture-selector
 #!/bin/bash
 
-[[ $(id -u -n) = "root" ]] && home=/home/"${SUDO_USER:-$USER}" || home=/home/"${USER}"
-directory="${HOME}"/.config
-process="$directory/conky-picture-frame/conky-picture-framerc"
+process="${directory}"/conky-picture-frame/conky-picture-framerc
 
 # specify source image
 
-source=$(zenity --file-selection --separator=$'\n' --title="Select a Directory") 2> /dev/null || exit  location or exit on 'Cancel'
-dimension="full" # small | medium | large | full / 25% | 50% | 75% | 100%
+dimension="full"
 
-# Set dimension flags
+# small:  25%
+# medium: 50%
+# large:  75%
+# full:   100%
 
-if [ "$dimension" == "small" ]
+source=$(zenity --file-selection --separator=$'\n' --title="Select a Directory") 2> /dev/null || exit'
+
+# set dimension flags
+
+if [ "${dimension}" == "small" ]
 then
-	ratio="128x" # canvas at 25%
-elif [ "$dimension" == "medium" ]
+	# canvas at 25%
+
+	ratio="128x"
+
+elif [ "${dimension}" == "medium" ]
 then
-	ratio="256x" # canvas at 50%
-elif [ "$dimension" == "large" ]
+	# canvas at 50%
+
+	ratio="256x"
+
+elif [ "${dimension}" == "large" ]
 then
-	ratio="384x" # canvas at 75%
-elif [ "$dimension" == "full" ]
+	# canvas at 75%
+
+	ratio="384x"
+
+elif [ "${dimension}" == "full" ]
 then
-	ratio="512x" # canvas at 100%
+	# canvas at 100%
+
+	ratio="512x"
 fi
 
-# Cleanup files
+# cleanup files
 
 if [[ -e .picture.png ]]
 then
 	rm -rf .picture.png
 fi
 
-# Picture frame compositor
+# picture frame compositor
 
-convert "$source" -resize "$ratio" .picture.png
+convert "${source}" -resize "${ratio}" .picture.png
 
-# Get dimensions
+# get dimensions
 
 dimensions=$(identify .picture.png | awk '{print $3}')
 
 IFS='x'
 read width height <<< "$dimensions"
 
-# Send result to conky
+# send result to conky
 
-sed -i -e "s/^minimum_size\ .*/minimum_size $width $height/g" "$directory"/conky-picture-frame/conky-picture-framerc
+sed -i -e "s/^minimum_size\ .*/minimum_size ${width} ${height}/g" "${directory}"/conky-picture-frame/conky-picture-framerc
 
 wait
 
@@ -67,11 +72,11 @@ echo "${image .picture.png}"
 
 wait
 
-sudo kill -SIGTERM $(pgrep -f "$process")
+sudo kill -SIGTERM $(pgrep -f "${process}")
 
 wait
 
-conky -c "$process"&
+conky -c "${process}" &
 FILE
 
 chmod +x /usr/bin/conky-picture-selector
