Code & Features Update

diff --git a/utility-rclone-google-drive b/utility-rclone-google-drive
--- a/utility-rclone-google-drive
+++ b/utility-rclone-google-drive
@@ -37,13 +37,15 @@ fi
 
 # superuser ////////////////////////////////////////////////////////////////////
 
+frobulator.escalate
+
 # script ///////////////////////////////////////////////////////////////////////
 
 script=$(basename -- "${BASH_SOURCE[0]}")
 
 # version //////////////////////////////////////////////////////////////////////
 
-version="08-31-2024"
+version="09-04-2024"
 
 # usage ////////////////////////////////////////////////////////////////////////
 
@@ -57,6 +59,8 @@ frobulator.script "Setting up ${script#*-}"
 
 # functions ////////////////////////////////////////////////////////////////////
 
+# defaults /////////////////////////////////////////////////////////////////////
+
 list=(
 	rclone
 	rclone-browser
@@ -65,6 +69,8 @@ list=(
 frobulator.require "${list[@]}"
 
 list=()
+
+# configuration
 
 if [ -d /media/[iI]nternal/[rR][cC]lone ]
 then
@@ -79,47 +85,111 @@ then
 	fi
 fi
 
+# script
+
 cat <<- 'FILE' > /usr/bin/rclone-google-drive
 #!/bin/bash
 
-synchronization_option="bisync"
+# variables ////////////////////////////////////////////////////////////////////
+
 cloud_server_directory="Google:"
 local_server_directory="/media/internal"
 
+# functions ////////////////////////////////////////////////////////////////////
+
+rclone_transfer () {
+
+	streams="16"
+
+	synchronization_option="${1}"
+
+	source="${2}"
+	destination="${3}"
+
+	exclude="${4}"
+
+	unset transfer_command
+
+	transfer_command+="rclone"
+	transfer_command+=" ${synchronization_option}"
+	transfer_command+=" ${source}"
+	transfer_command+=" ${destination}"
+	transfer_command+=" --create-empty-src-dirs"
+	transfer_command+=" --drive-skip-gdocs"
+
+	if [ ! -z "${4}" ]
+	then
+		exclude="/${exclude}/**"
+
+		transfer_command+=" --exclude ${exclude}"
+	fi
+
+	transfer_command+=" --multi-thread-streams ${streams}"
+	transfer_command+=" --progress"
+	transfer_command+=" --verbose"
+
+	exec  ${transfer_command}
+}
+
+# copy /////////////////////////////////////////////////////////////////////////
+
+# google drive >>> local machine
+
+synchronization_option="copy"
+
 exclude="/Music/**"
-compare="size,modtime,checksum"
-lock="2m"
-resolve="newer"
-streams="12"
+streams="16"
 
-local_directories_list=( $(find "${local_server_directory}" -mindepth 1 -maxdepth 1 -type d ! -iname "*.Trash*" -exec basename {} \;) )
+echo "Copying"
+echo
 
-for directory in ${local_directories_list[@]}
+rclone_transfer copy "${cloud_server_directory}/" "${local_server_directory}/" Music
+
+synchronization_option="sync"
+
+# synchronize //////////////////////////////////////////////////////////////////
+
+# local machine >>> google drive
+
+echo "Synchronizing"
+echo
+
+server_directories_list=(
+	$(find "${local_server_directory}"	\
+		-mindepth 1						\
+		-maxdepth 1						\
+		-type d							\
+		! -iname "*.Trash*"				\
+		! -iname "Git"					\
+		! -iname "Music"				\
+			-exec basename {} \;)
+)
+
+for server_directory in ${server_directories_list[@]}
 do
-	rclone 																													\
-		"${synchronization_option}" "${cloud_server_directory}"/"${directory}" "${local_server_directory}"/"${directory}"	\
-			--exclude="${exclude}"																							\
-			--compare "${compare}"																							\
-			--slow-hash-sync-only																							\
-			--resilient																										\
-			--max-lock "${lock}"																							\
-			--conflict-resolve "${resolve}"																					\
-			--drive-skip-gdocs																								\
-			--fix-case																										\
-			--multi-thread-streams "${streams}"																				\
-			--recover																										\
-			--resilient																										\
-			--verbose
+	echo "${server_directory}"
+	echo
+
+	rclone_transfer sync "${local_server_directory}/${server_directory}" "${cloud_server_directory}/${server_directory}"
 done
 
-local_directories_list=()
+echo "Music"
+echo
+
+rclone_transfer sync "/media/nathanel/Samsung T7/Music/STEYOYOKE" "${cloud_server_directory}/Music/STEYOYOKE"
+
+rclone_transfer sync "/media/nathanel/Samsung T7/Music/INNER SYMPHONY" "${cloud_server_directory}/Music/INNER SYMPHONY"
 FILE
+
+# permissions
 
 chmod +x "${HOME}"/.local/bin/rclone-google-drive
 
+# service
+
 frobulator.directory "${HOME}" .config/systemd/user
 
-# timer
+# service timer
 
 cat <<- 'FILE' > "${HOME}"/.config/systemd/user/rclone-google-drive.timer
 [Unit]
@@ -133,7 +203,7 @@ Persistent=true
 WantedBy=timers.target
 FILE
 
-# service
+# service desciptor
 
 cat <<- 'FILE' > "${HOME}"/.config/systemd/user/rclone-google-drive.service
 [Unit]
@@ -143,6 +213,8 @@ Description=Synchronize Google Drive using RClone every 5 minutes
 ExecStart=/usr/bin/bash /usr/bin/rclone-google-drive
 FILE
 
+# service activation
+
 systemctl enable --user rclone-google-drive.timer
 systemctl start --user rclone-google-drive.timer
 
@@ -150,6 +222,12 @@ if [[ $(systemctl list-timers --user | grep -o rclone-google-drive) ]]
 then
 	echo "Service activation successful"
 	echo
+else
+	echo "Error"
+	echo
+
+	exit 1
+
 fi
 
 frobulator.cpt "Complete" "[ Service Launch ]"
